### ISSUE TITLE
Add specs for UberTask on_report and on_retry methods

### ISSUE THREAD

**Issue by alkesh26** [shakacode/uber_task#5]
The code coverage report for `on_retry` and `on_report` methods is 0.
<img width="491" alt="Screenshot 2023-12-21 at 2 00 00 PM" src="https://github.com/shakacode/uber_task/assets/1019076/c9571449-9bd8-41b6-a397-82b0c9f3591d">

**Comment by borela** [comment]
Done in https://github.com/shakacode/uber_task/pull/22
